[package]
name = "web-service"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.98"
axum = "0.8.3"
tokio = {version = "1.44.2", features = ["full"] }
serde = { version = "1.0.219", features = ["derive"] }
